[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["Vector", "Store", "Vendor/Weaviate", "Area/AI", "Type/Util"]
license = ["Apache-2.0"]
name = "ai.weaviate"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.weaviate"
version = "@toml.version@"

[platform.java21]
graalvmCompatible = true
